"""create_receipts_and_items_tables

Revision ID: d520449d3cae
Revises: 
Create Date: 2026-01-13 06:54:14.795640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd520449d3cae'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('receipt_number', sa.String(length=20), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=False),
    sa.Column('customer_nit', sa.String(length=50), nullable=True),
    sa.Column('customer_phone', sa.String(length=50), nullable=True),
    sa.Column('customer_email', sa.String(length=255), nullable=True),
    sa.Column('date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('signature', sa.Text(), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), server_default='0.00', nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), server_default='0.00', nullable=False),
    sa.Column('custom_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_receipts_created_at', 'receipts', ['created_at'], unique=False)
    op.create_index(op.f('ix_receipts_customer_name'), 'receipts', ['customer_name'], unique=False)
    op.create_index(op.f('ix_receipts_customer_nit'), 'receipts', ['customer_nit'], unique=False)
    op.create_index(op.f('ix_receipts_date'), 'receipts', ['date'], unique=False)
    op.create_index(op.f('ix_receipts_receipt_number'), 'receipts', ['receipt_number'], unique=True)
    op.create_table('receipt_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('receipt_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), server_default='1.00', nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), server_default='0.00', nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), server_default='0.00', nullable=False),
    sa.Column('line_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['receipt_id'], ['receipts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_receipt_items_receipt_id'), 'receipt_items', ['receipt_id'], unique=False)
    op.create_index('ix_receipt_items_receipt_line', 'receipt_items', ['receipt_id', 'line_order'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_receipt_items_receipt_line', table_name='receipt_items')
    op.drop_index(op.f('ix_receipt_items_receipt_id'), table_name='receipt_items')
    op.drop_table('receipt_items')
    op.drop_index(op.f('ix_receipts_receipt_number'), table_name='receipts')
    op.drop_index(op.f('ix_receipts_date'), table_name='receipts')
    op.drop_index(op.f('ix_receipts_customer_nit'), table_name='receipts')
    op.drop_index(op.f('ix_receipts_customer_name'), table_name='receipts')
    op.drop_index('ix_receipts_created_at', table_name='receipts')
    op.drop_table('receipts')
    # ### end Alembic commands ###
